# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sample <- function(init_state, n_samples, thin_interval = 1L, burnin_interval = 0L) {
    .Call('_BDD_sample', PACKAGE = 'BDD', init_state, n_samples, thin_interval, burnin_interval)
}

